services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - datasdas:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    
volumes:
  data: {}
