#!/bin/bash

: "${FORGE_VERSION:=${FORGEVERSION:-RECOMMENDED}}"
: "${FORGE_FORCE_REINSTALL:=false}}"

# shellcheck source=start-utils
. "${SCRIPTS:-$(dirname "$0")}/start-utils"
isDebugging && set -x


# Lista de URLs de los mods (enlaces de descarga directa desde OneDrive)
apt-get update && apt-get install -y unzip
MOD_URLS=(
  "
https://jgalqq.sn.files.1drv.com/y4mM7ejJYUqZDr9eJve3Y4TQvLi5DrxCkakIpJjF-5Pt9HK28ZyGFI-AQN84Zh2K0pxbuOeVn2Sio-k0p23NpBBiGLI-we-m685AwG_ffxw18liTUgASyxTNnKStRB-d1BM-uTwMSJ6GbqTiGpY1ZnSydN-mjS4QAoJZNjs3PB4HOYyRTZRhCcIuc76VuZs0PZqG-C7iyYFHn4117DZqpgE2w"
)




if [[ ${FORGE_INSTALLER} ]]; then
  if ! mc-image-helper install-forge \
    wget -O /tmp/$(basename $MOD_URL) $MOD_URL \
    unzip -o /tmp/$(basename $MOD_URL) -d /data/mods \
    --output-directory=/data \
    --results-file=/data/.run-forge.env \
    --minecraft-version="${VERSION}" \
    --forge-installer="${FORGE_INSTALLER}" \
    --force-reinstall="${FORGE_FORCE_REINSTALL}"; then
      log "ERROR failed to install Forge given installer ${FORGE_INSTALLER}"
      exit 1
  fi

else
  if ! mc-image-helper install-forge \
    --output-directory=/data \
    --results-file=/data/.run-forge.env \
    --minecraft-version="${VERSION}" \
    --forge-version="${FORGE_VERSION}" \
    --force-reinstall="${FORGE_FORCE_REINSTALL}"; then
      log "ERROR failed to install Forge"
      exit 1
  fi

fi


# grab SERVER and export it
set -a
source /data/.run-forge.env
set +a

export FAMILY=FORGE

exec "${SCRIPTS:-/}start-setupWorld" "$@"
